### PR TITLE
Add check for code completeness

### LINKED ISSUE #16: Implement code completeness
Problem: We execute only a single line of what the user typed, not allowing for functions, classes, etc. in Python

Solution: Rely on `is_complete_request` to determine to not send yet

Spec: http://jupyter-client.readthedocs.org/en/latest/messaging.html#code-completeness

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #16.

cc: @rgbkrk

### CODE REVIEW

**Comment by rgbkrk** [comment]
Nice!

**Comment by rgbkrk** [comment]
Tried this out today, seems not every kernel implements this properly. At least for the IJavascript Kernel, it hung waiting:

```
$ node index.js javascript
IJavascript v5.0.0
https://github.com/n-riesco/ijavascript
ick.js:1> 324


Have a great day!
^C
```

For the Python kernel (and likely any other), we'll want to provide indent.

```
ick.py:2> def wat():
  print(23)

```

**Comment by captainsafia** [comment]
Poops! This is why we need tests!

I've opened up #27 and #28 to follow up on these issues.

**Comment by rgbkrk** [comment]
Tests are great.

Trying things out a bit is good to shake out what the experience of a feature is like as well. :wink:

**Pull request merged**
