### PR TITLE
Use enchannel helper functions

### PR DESCRIPTION
**Pull request by jdfreder**
I believe these are the changes required for the new helper functions introduce in https://github.com/nteract/enchannel/pull/9 .  **Make sure to publish enchannel before merging**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looks like we'll also need a Travis file for `ick`, unrelated to this PR.

**Comment by rgbkrk** [comment]
I put up a PR before making a release: https://github.com/nteract/enchannel/pull/10

**Comment by rgbkrk** [comment]
Are you picking this one up now that we've taken in all the other changes?

**Comment by jdfreder** [comment]
Sure, I'll look at this separate to this PR

**Pull request closed without merging**
